### ISSUE TITLE
CarrierWave requires 'fog' gem, rather than say 'fog-aws'

### ISSUE THREAD

**Issue by graft** [carrierwaveuploader/carrierwave#1648] opened 2015-05-12 22:41 UTC
If I do:

require 'fog'
require 'carrierwave'

all is well.

However, if the 'fog' gem is not installed, but 'fog-aws' is, and I do:

require 'fog/aws'
require 'carrierwave'

I get a LoadError: cannot load such file -- fog

This is surely an error?

**Comment by fran-worley** [comment] 2015-05-21 08:55
Looking at the readme, the current release v0.10.0 requires 'fog' and not 'fog-aws'. The master branch (and therefore future release v1.0.0) will use 'fog-aws' instead.

To get 'fog-aws' to work now you will need to use the master branch, or continue to use 'fog' until v1.0.0 is released.

**Comment by plribeiro3000** [comment] 2015-05-21 12:03
@fran-worley :+1: 

With this new structure in `fog` i believe that the automatic load will be removed and thus the responsibility of doing so will be in the hands of the developer itself. I know this sounds as a regression but is one step in the direction of making `fog` a little more modular and require less code since most of the projects use only one provider and not all of them at once.

Thank you for taking the time to read the README and answer this!

**Comment by fran-worley** [comment] 2015-05-21 12:07
I actually think that it is a great improvement and thank you for all your work on the gem it's a life saver! Any idea on when v1.0.0 might be released?

**Comment by plribeiro3000** [comment] 2015-05-21 12:08
I'm not well into `carrierwave` yet but i believe the top priorities are to make it hit the streets asap.

**Closed** 2015-06-03 19:11 UTC

**Comment by mdesantis** [comment] 2016-11-29 16:04
I have this issue even with 1.0.0.rc:

```ruby
# Gemfile
gem 'carrierwave', '>= 1.0.0.rc', '< 2.0'
gem 'fog-aws', group: :production
```

`rails server` booting error:

```
/home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- fog (LoadError)
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/carrierwave-1.0.0.rc/lib/carrierwave/uploader/configuration.rb:121:in `eager_load_fog'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/carrierwave-1.0.0.rc/lib/carrierwave/uploader/configuration.rb:136:in `fog_credentials='
	from /home/maurizio/Sviluppo/dday.it/config/initializers/fog.rb:2:in `block in <top (required)>'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/carrierwave-1.0.0.rc/lib/carrierwave/uploader/configuration.rb:158:in `configure'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/carrierwave-1.0.0.rc/lib/carrierwave.rb:14:in `configure'
	from /home/maurizio/Sviluppo/dday.it/config/initializers/fog.rb:1:in `<top (required)>'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:652:in `block in load_config_initializer'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:651:in `load_config_initializer'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:615:in `each'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:615:in `block in <class:Engine>'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `each'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/2.3.0/tsort.rb:415:in `call'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/railtie.rb:194:in `public_send'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/railtie.rb:194:in `method_missing'
	from /home/maurizio/Sviluppo/dday.it/config/environment.rb:5:in `<top (required)>'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/maurizio/Sviluppo/dday.it/config.ru:3:in `block in <main>'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `instance_eval'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `initialize'
	from /home/maurizio/Sviluppo/dday.it/config.ru:in `new'
	from /home/maurizio/Sviluppo/dday.it/config.ru:in `<main>'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:49:in `eval'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:49:in `new_from_string'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:40:in `parse_file'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/server.rb:208:in `app'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/server.rb:61:in `app'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/server.rb:336:in `wrapped_app'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/server.rb:139:in `log_to_stdout'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/server.rb:78:in `start'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/maurizio/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by fourcolors** [comment] 2017-01-07 09:52
@mdesantis I can confirm I'm getting this same message. It seems to be recent.

**Comment by JesseLisby** [comment] 2017-01-08 20:54
I'm having this same issue today

**Comment by mrancys** [comment] 2017-01-09 15:42
Same issue today

**Comment by mdesantis** [comment] 2017-01-09 17:02
If can help I resolved in this way:

```ruby
# Gemfile
gem 'fog-aws', group: :production
gem 'carrierwave', '~> 1.0'

# initializer
require 'carrierwave/storage/abstract'
require 'carrierwave/storage/file'
require 'carrierwave/storage/fog'

CarrierWave.configure do |config|
  if Rails.env.production?
    config.storage :fog
    config.fog_provider = 'fog/aws'
    config.fog_credentials = {
      provider:              'AWS',
      [...]
    }
    [...]
  else
    config.storage :file
    config.enable_processing = false if Rails.env.test?
  end
end
```

**Comment by installero** [comment] 2017-02-05 18:38
`config.fog_provider = 'fog/aws'` helped

**Comment by inkstak** [comment] 2017-02-10 09:16
Upgrading to Carrierwave 1.0.0, I confirm I needed @mdesantis solution to resolve the issue

```
# config/initializers/carrierwave.rb

require 'carrierwave/storage/abstract'
require 'carrierwave/storage/file'
require 'carrierwave/storage/fog'

(..)

config.fog_provider = 'fog/aws'
```

**Comment by Mattensor** [comment] 2017-02-19 05:27
Thanks Mdesantis requiring the correct carrierwave/storage files worked for me

**Comment by seans84** [comment] 2017-04-07 02:21
Thanks mdesantis, did the trick

**Comment by tonytonyjan** [comment] 2017-06-23 14:28
Why was this thread being closed?

**Comment by kstack7** [comment] 2017-07-26 05:15
Thanks, @mdesantis -- heroku build was spitting back at me, but the combo of adding required files and specifying fog_provider did the trick 👍  kudos!

**Comment by petrbela** [comment] 2018-01-10 18:56
It also seems that `fog_provider = 'fog/aws'` has to be set *before* setting `fog_credentials`.

**Comment by dgreen22** [comment] 2018-01-14 04:10
Worked for me too. Thanks @mdesantis
