### ISSUE TITLE
undefined method `push'

### ISSUE THREAD

**Issue by jonathanng** [carrierwaveuploader/carrierwave#1629] opened 2015-04-21 23:32 UTC
def mogrify(options = {})
      manipulate! do |img|
        img.format("png") do |c|
          # this doesn't work anymore
          c.push '+profile'
        end
        img
      end
    end

https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Efficiently-converting-image-formats#full-example

Apparently, c.push doesn't work anymore:

    NoMethodError: undefined method `push' for #<MiniMagick::Tool::Convert:0x007f86869d0288>

**Comment by eavgerinos** [comment] 2015-04-22 06:16
I believe this is a duplicate of #1520.

If so, can you please comment your case there and close this issue? :)

Thanks for reporting.

**Closed** 2015-04-22 11:54 UTC

**Comment by kreintjes** [comment] 2015-07-29 09:36
Hi @jonathanng I ran into the same issue as you. Apparently in MiniMagick 4.x the syntax for + args, like +profile, is changed. Instead of `c.push '+profile'` followed with a `c.+` with the arguments, you can now simply do `c.profile.+ 'args'`.

I have updated the how-to on the wiki, see https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Efficiently-converting-image-formats for more information.
