### ISSUE TITLE
undefined method identifier with multiple files upload

### ISSUE THREAD

**Issue by Jojoooo1** [carrierwaveuploader/carrierwave#2180] opened 2017-05-18 18:43 UTC
Hello, 

I am currently trying to implemente multiple files upload following this tutorial  http://bobintornado.github.io/rails/2015/12/29/Multiple-Images-Uploading-With-CarrierWave-and-PostgreSQL-Array.html . With single file upload it work properly, but when I am switching to multiple and setting mount_uploaderS, I always got this error message. I am using rails 5.0.0 and last version of carrierwave. 

NoMethodError - undefined method `identifier' for #<ActionDispatch::Http::UploadedFile:0x007f5f98015618>:
   () usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/carrierwave-07dc4d7bd780/lib/carrierwave/mounter.rb:25:in `identifiers'
   () usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/carrierwave-07dc4d7bd780/lib/carrierwave/mount.rb:334:in `write_images_identifier'

OR this one if trying to save my record when debugging using pry :

NoMethodError: undefined method `identifier' for #<ActionDispatch::Http::UploadedFile:0x00557291690358>
from /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/carrierwave-07dc4d7bd780/lib/carrierwave/mounter.rb:25:in `map'

I would greetly appreciate your help.
Have a good day.

Jonathan

**Comment by BigChief45** [comment] 2017-08-19 00:28
I am also experiencing a similar issue.

No error, but when using something like:

```haml
- @attachments.each do |a|
     %li= a.identifier
```

Nothing is returned.

**Comment by BrusGarka** [comment] 2017-10-19 22:05
Duplicate of #1581

**Closed** 2019-05-08 08:12 UTC
