### ISSUE TITLE
cache directory can't delete.

### ISSUE THREAD

**Issue by MatsumotoHiroko** [carrierwaveuploader/carrierwave#2113] opened 2017-02-03 04:41 UTC
I want to delete temporary files for uploading on carrierwave.
I don't to set a parameter of "config.delete_tmp_file_after_storage". (This parameter is true as default.)
But My temporary files can't delete after uploading.
Do you know this problem?

**My environment**
```
Ubuntu 16.04LTS
ruby 2.4.0p0 (2016-12-24 revision 57164)
rails 5.0.1
carrierwave 1.0.0
fog 1.38.0
```

**config/initializers/carrierwave.rb**
```
CarrierWave.configure do |config|
  config.fog_credentials = {
    provider:              'AWS',
    region:                'xxxxxxxx'
  }.merge Settings.fog_credentials || {}

  # For testing, upload files to local `tmp` folder.
  if Rails.env.test? || Rails.env.cucumber?
    config.storage = :file
    config.enable_processing = false
    config.root = "#{Rails.root}/tmp"
  else
    config.storage = :fog
  end

  config.fog_directory = Settings.fog_directory
  config.fog_public    = true
  # use Japanese
  CarrierWave::SanitizedFile.sanitize_regexp = /[^[:word:]\.\-\+]/
end

```

**base_image_uploader.rb**
```
class BaseImageUploader < ImageUploader
  ......

  def move_to_store
    true
  end

  def move_to_cache
    true
  end

  def cache_dir
    "/tmp/uploads/images"
  end

  ......
end
```

**after uploading, temporary directory's status**
```
ubuntu@ip-xxxxxxxx:/tmp/uploads/images/1486091031-30865-0001-5400$ ls
code_1.jpg  code_big_1.jpg  code_normal_1.jpg  code_thumb_1.jpg
```

**Comment by reggieb** [comment] 2017-02-22 10:32
I'm getting a similar problem. I think the root of the issue is that the location of the `cache_dir` is not the default location. If you look at [`clean_cache!` method in `file.rb`](https://github.com/carrierwaveuploader/carrierwave/blob/fa9d1e3d301b03cf2e8457a530c162265f439bf2/lib/carrierwave/storage/file.rb):

      def clean_cache!(seconds)
        Dir.glob(::File.expand_path(::File.join(uploader.cache_dir, '*'), CarrierWave.root)).each do |dir|
          # generate_cache_id returns key formated TIMEINT-PID-COUNTER-RND
          time = dir.scan(/(\d+)-\d+-\d+-\d+/).first.map(&:to_i)
          time = Time.at(*time)
          if time < (Time.now.utc - seconds)
            FileUtils.rm_rf(dir)
          end
        end
      end

Notice that on the second line the `uploader.cache_dir` is generated relative to `CarrierWave.root` (via `.expand_path`). On my system, `CarrierWave.root` is my apps `public` folder.

So in @MatsumotoHiroko's example, `clean_cache!` will try to remove files from `/path/to/public/tmp/uploads/images` and not `/tmp/uploads/images`

Therefore, if the cache directory is set to be outside the public folder, `clean_cache!` will always fail.

**Comment by reggieb** [comment] 2017-02-22 10:48
Actually, looking at the code again, all the file operations appear to be relative to 'CarrierWave.root' or 'uploader.root' (which appears to point at the same location). So I'm not sure how @MatsumotoHiroko is getting files into `/tmp/uploads/images`.

  ```
def cache_dir
    "/tmp/uploads/images"
  end
```

will generate a path relative to `CarrierWave.root` and not the relative to system root.

**Comment by aledalgrande** [comment] 2017-04-04 08:49
He is setting Carrierwave's root with `Rails.root`, when the latter has not been initialized yet. Which means `"#{Rails.root}/tmp"` becomes `"/tmp"`, an absolute path.

**Comment by marcoadkins** [comment] 2020-09-11 20:44
A hacky workaround for this is to call the clean cache method directly on your instance of uploader. Something like:
```ruby
CustomUploader.cache_storage.new(CustomUploader.new).clean_cache! 24
```

Would be good to get something like this implemented on the uploader instance so it could be called directly.

**Comment by marcoadkins** [comment] 2020-09-11 20:49
@mshibuya Was this resolved in some way? I see it was closed but there doesn't seem to be any sort of proper solution here.

**Closed** 2023-03-18 10:33 UTC
