### ISSUE TITLE
No method error for cache!

### ISSUE THREAD

**Issue by ghost** [carrierwaveuploader/carrierwave#2267] opened 2018-01-08 14:52 UTC
I am following this tutorial to clean up the directory temp : [link](https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Delete-cache-garbage-directories)
, but I am getting no method error when upload: > private method `cache!' called for

**Comment by jpatters** [comment] 2018-01-10 23:05
I had this issue too. That page must be out of date. I dug into the source and found that `cache!`  has a default parameter. Use this instead:
```ruby
class FileUploader < CarrierWave::Uploader::Base
  after :store, :delete_old_tmp_file

  def sanitized_file
    super
  end

  # remember the tmp file
  def cache!(new_file = sanitized_file)
    super
    @old_tmp_file = new_file
  end

  def delete_old_tmp_file(dummy)
    @old_tmp_file.try :delete
  end
end
```

That wiki page should probably be updated.

**Comment by jpatters** [comment] 2018-01-10 23:22
I am actually currently debugging an issue that it turns out is caused by this code. The reference to the temp file (`@old_tmp_file`) is not being closed so when resizing a lot of images I am getting a `Too many open files` error. The problem is that if I try closing the file on delete, not all of my versions get created. If I find a solution I will respond with my code, but just a caveat to be aware of. This doesn't work if you are creating more than one version.

**Comment by jpatters** [comment] 2018-01-11 18:23
I just confirmed that the code above is not what was causing the `Too many open files` error. So disregard my previous comment. It is working fine for me.

**Closed** 2019-05-01 08:54 UTC
