### ISSUE TITLE
Uploading multiple images with same image name doesn't work

### ISSUE THREAD

**Issue by take** [carrierwaveuploader/carrierwave#1855] opened 2016-01-31 04:19 UTC
## Ideal behavior

Maybe an automatical image name update something `omg.png, omg.png` to `omg.png, omg_2.png`?
## Current behavior

DB column value ends up like `["omg.png", "omg.png"]`, but only the first image is actually uploaded.
Same thing happens when I use the [unique filename strategy](https://github.com/carrierwaveuploader/carrierwave/wiki/How-to%3A-Create-random-and-unique-filenames-for-all-versioned-files#unique-filenames)(same filename but only 1 image uploaded).

BTW I found out that this happens when using iPhone to upload images :)

multiple file upload feature was added in https://github.com/carrierwaveuploader/carrierwave/pull/1481

**Comment by take** [comment] 2016-01-31 09:04
I guess we can avoid this problem if we change `store_dir` from

`"uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"`

to

"uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}/#{INDEX OF THE FILE}/"

**Comment by thomasfedb** [comment] 2016-02-01 12:16
This is definitely an issue that I want to look into closely.

**Comment by Silex** [comment] 2016-02-01 17:38
While you're at it, how do we do different store_dir with the _same_ file name?

Here is what I tried, but it fails because I guess it deletes the same cache file twice (it works if I let the filename be different, with the foo_ or bar_ being prefixed).

``` ruby
  def store_dir
    "/data/#{version_name}"
  end

  def filename
    "#{model.id}.data" if original_filename.present?
  end

  version :foo do
    def full_filename(for_file)
      for_file
    end
  end

  version :bar do
    def full_filename(for_file)
      for_file
    end
  end
```

**Comment by connorshea** [comment] 2016-09-28 04:09
#2029 might be a duplicate of this, or at least a similar problem? @take any more info you can provide?

**Closed** 2023-05-28 10:14 UTC
Labels: bug
