### ISSUE TITLE
uninitialized constant CarrierWave::Storage::Fog (NameError)

### ISSUE THREAD

**Issue by rjsnh1522** [carrierwaveuploader/carrierwave#2228] opened 2017-09-20 11:04 UTC
gem 'carrierwave', '~> 1.0'
gem "fog-aws"

I am trying to upload file to user's provided aws credentials for this I used.
I did some this from this url [https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Define-different-storage-configuration-for-each-Uploader.](url) 

` def get_credentials
    	active_type=UploadManagement.find_by_is_active(1)
    	if active_type.present? &&  active_type.provider == "aws"
	    	fog_credentials = {
	          :provider               => 'AWS',              # required
	          :aws_access_key_id      => active_type.access_key,     # required
	          :aws_secret_access_key  => active_type.secret_key,    # required
	          :asset_host             => 'https://s3-ap-northeast-1.amazonaws.com'
	        }
	        fog_directory = "YOURBUCKET"
	        fog_provider = 'fog/aws'
	    end
    end`

still I am getting uninitialized constant CarrierWave::Storage::Fog (NameError)

i also tried searching but didnt find solution.

I need to do like if user has aws credentials then upload to aws else save file to local.

**Comment by vanitu** [comment] 2017-10-18 14:12
+1 have same issue

**Comment by vanitu** [comment] 2017-10-18 14:19
I found a solution. 
I put storage setup after configuration. And it works

configure do |config|
    config.fog_provider = 'fog/aws' # required
    ....
end

storage  :fog

**Comment by biologistbrian** [comment] 2017-10-24 01:27
U check ur aws?  I did that, seemed to work, but it was just storing it locally and the file didn't appear on AWS

**Comment by gorenje** [comment] 2017-11-14 12:57
Same solution as @vanitu, in my case I was doing the initializing using Glob:

```
Dir[File.join(File.dirname(__FILE__),'config','initializers','*.rb')].
  each { |a| require a }
```
Which caused the database to be initialized first, including the models that defined ```storage :fog```

I changed it to doing it explicitly:

```
require_relative 'config/initializers/carrierwave'
require_relative 'config/initializers/database'
```
and everything worked consistently.

Strangely, locally I never got the error, only when deploying to Heroku and then only sporadically.

**Comment by FunkyloverOne** [comment] 2017-12-13 19:21
Hey @rjsnh1522, your issue seems to be duplicate of this:
https://github.com/carrierwaveuploader/carrierwave/issues/2023
and it already has a solution.

**Comment by mshibuya** [comment] 2019-05-08 08:16
Dup of #2023, solution is [here](https://github.com/carrierwaveuploader/carrierwave/issues/2023#issuecomment-252407542).

**Closed by mshibuya** 2019-05-08 08:16 UTC
