### ISSUE TITLE
The code depends on `@original_filename` doesn't work since v3.0.4

### ISSUE THREAD

**Issue by y-yagi** [carrierwaveuploader/carrierwave#2708] opened 2023-10-11 01:22 UTC
The `uploader.rb` generated by generators has an example of how to override the filename. The code is the following.

https://github.com/carrierwaveuploader/carrierwave/blob/0c50a8bc7d1c39fe15be056fb22c7b110b9815ae/lib/generators/templates/uploader.rb.erb#L42-L46

But, I think this code doesn't work since v3.0.4 because `@original_filename` is set to nil after `store` by #2707.

So that example always returns `nil` now.  The reproduction script is the following.

```ruby 
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "activerecord"
  gem "sqlite3"
  # gem "carrierwave", "3.0.3"
  gem "carrierwave", "3.0.4"
end

require "active_record"
require "carrierwave"
require "carrierwave/orm/activerecord"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(File::NULL)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :name
    t.string :avatar
  end
end

class AvatarUploader < CarrierWave::Uploader::Base
  storage :file

  def filename
    "sanitized_filename.txt" if original_filename
  end
end

class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
end

class BugTest < Minitest::Test
  def test_filename
    u = User.new
    File.open("test.txt") { |f| u.avatar = f }
    u.save!
    assert_equal "sanitized_filename.txt", u.avatar.filename
  end
end
```

```bash
$ ruby bug_report_carrierwave.rb
# Running:

F

Finished in 0.008341s, 119.8938 runs/s, 119.8938 assertions/s.

  1) Failure:
BugTest#test_filename [bug_report_carrierwave.rb:48]:
Expected: "sanitized_filename.txt"
  Actual: nil

1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

Is this an intended change?

**Comment by RachalCassity** [comment] 2023-10-19 14:36
We are also facing this same issue,

In previous versions, the original filename would be stored when called `uploader.store!(file)`. Going through each line, the 
only change was when store! was called. 

 I noticed this [commit](https://github.com/carrierwaveuploader/carrierwave/commit/cfaf173b9f94b1ae3cb705f8b3eb1a55a8200921) reassigns the original_filename. 
 
`carrier wave 3.0.3:
attachment_uploader
=> #<Uploader:0x000000014bb1da90
 @cache_id=nil,
 @cache_storage=
  #<CarrierWave::Storage::File:0x000000014be92c48
   @cache_called=nil,
   @uploader=#<Uploader:0x000000014bb1da90 ...>>,
 @deduplication_index=nil,
 @file=
  #<CarrierWave::SanitizedFile:0x000000011b0d3ad8
   @content=nil,
   @content_type=nil,
   @declared_content_type="application/pdf",
   @file=
    "....pdf",
   @original_filename=nil>,
 @filename="extras.pdf",
 @guid="ec45bd9e-4497-43ef-8bd3-7c578e127485",
 @identifier="extras.pdf",
 @model="ec45bd9e-4497-43ef-8bd3-7c578e127485",
 @mounted_as=nil,
 @original_filename="....pdf",
 @staged=false,
 @storage=
  #<CarrierWave::Storage::File:0x000000014be914b0
   @cache_called=nil,
   @uploader=#<Uploader:0x000000014bb1da90 ...>>,
 @versions={}>`



`carrierwave 3.0.4:

attachment_uploader
=> #<Uploader:0x00000001595fe920
 @cache_id=nil,
 @cache_storage=
  #<CarrierWave::Storage::File:0x0000000159c14300
   @cache_called=nil,
   @uploader=#<Uploader:0x00000001595fe920 ...>>,
 @deduplication_index=nil,
 @file=
  #<CarrierWave::SanitizedFile:0x000000011faad668
   @content=nil,
   @content_type=nil,
   @declared_content_type="application/pdf",
   @file=
    "......pdf",
   @original_filename=nil>,
 @filename=".pdf",
 @guid="d0d65670-d87a-4a92-8d70-fe5d948e9741",
 @identifier=".pdf",
 @model="d0d65670-d87a-4a92-8d70-fe5d948e9741",
 @mounted_as=nil,
 @original_filename=nil,
 @staged=false,
 @storage=
  #<CarrierWave::Storage::File:0x0000000159c12b40
   @cache_called=nil,
   @uploader=#<tUploader:0x00000001595fe920 ...>>,
 @versions={}>
`

**Comment by mshibuya** [comment] 2023-10-28 04:15
First, the example implementation

```
  def filename
    "sanitized_filename.txt" if original_filename
  end
```

is safeguarded with `if original_filename`, but it's just an workaround for the old issue #1898 and no longer necessary in CarrierWave 3.x. If you remove the conditional, `#filename` will always return a value.

Also I want to understand the real use case of that `#filename` call. What `#filename` stands for is not the actual name that the stored file has, but the name **you want it to be named**. For example, when you have

```
  def filename
    "#{Time.now.to_i}.jpg"
  end
```

the return value changes time to time and does not reflect the stored file's name. So it's not a stable way to get the filename.
For what purpose do you use the value of `#filename` ?

**Comment by rajyan** [comment] 2023-10-29 23:53
There is a note about changes in original_filename here
https://github.com/carrierwaveuploader/carrierwave/blob/master/README.md#changing-the-filename

and original_filename isn't the *original filename* as explained in https://github.com/carrierwaveuploader/carrierwave/pull/2710#issuecomment-1783704058

Although, it is still used in the generator, 
https://github.com/carrierwaveuploader/carrierwave/blob/0c50a8bc7d1c39fe15be056fb22c7b110b9815ae/lib/generators/templates/uploader.rb.erb#L42-L46

and https://github.com/carrierwaveuploader/carrierwave/commit/cfaf173b9f94b1ae3cb705f8b3eb1a55a8200921 was definitely a breaking change... 
I'm looking for a way to fix it without breaking this.

**Comment by y-yagi** [comment] 2023-10-30 02:12
I'm not sure about the detailed history, the code generated by the generator is wrong now, right?

https://github.com/carrierwaveuploader/carrierwave/blob/0c50a8bc7d1c39fe15be056fb22c7b110b9815ae/lib/generators/templates/uploader.rb.erb#L42-L46

If so, I'm OK with fixing our application code. But it looks like breaking change and introducing breaking change in a newer minor version violates semantic versioning. I think it's good to support old behavior at least in a minor update, what do you think?

**Comment by mshibuya** [comment] 2023-11-23 07:46
> https://github.com/carrierwaveuploader/carrierwave/commit/cfaf173b9f94b1ae3cb705f8b3eb1a55a8200921 was definitely a breaking change...

To tell if it actually is or not, it is important to understand the real use case. It can be either a behavior that should be considered as a specification, or that you're just depending on what happened to work in the past.

**Comment by mshibuya** [comment] 2024-01-13 05:39
As many people (including [this](https://github.com/carrierwaveuploader/carrierwave/pull/2710#issuecomment-1890319196)) seems to be struggling, I got an idea.
The problem is the safeguard `if original_filename` within `#filename` so if someone seems to have it we should be able to instruct them to remove it, in the form of warning. I can open a PR.

**Closed** 2024-02-04 09:16 UTC

**Comment by fabian-as** [comment] 2025-01-30 16:19
The Wiki still contains the outdated, wrong instructions: https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Create-random-and-unique-filenames-for-all-versioned-files#unique-filenames

**Comment by mshibuya** [comment] 2025-01-31 04:25
@fabian-as Wiki is editable for everyone! You can go ahead with fixing 🙏

**Comment by srghma** [comment] 2025-03-03 05:19
updated the wiki https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Create-random-and-unique-filenames-for-all-versioned-files/_compare/e8c8119836bb576a8d65d2bdac1dad1f3a83e274

was it correct?

**Comment by mshibuya** [comment] 2025-03-08 04:52
Perfect! 👍

**Comment by ralph** [comment] 2025-03-10 17:00
@srghma @mshibuya  I am not sure this is correct, or what people expect. So without storing the token in the database, this will lead to a new token being generated for each time the model is instantiated, no?

With the old way of `filename`ing (and `original_filename`), it was possible to just keep a once persisted filename. This does not seem to be possible any more without persisting all the parts (e.g. tokens, uploading timestamps) that make up the filename, am I wrong?

So if this is correct, the wiki page should state that all parts need to be persisted if one needs this functionality.
