### ISSUE TITLE
recreate_versions! prepends and appends version to filename

### ISSUE THREAD

**Issue by synoptase** [carrierwaveuploader/carrierwave#1362] opened 2014-04-08 08:45 UTC
Issue is quite similar to #1164, with some other side effect.

With this model

``` ruby
require 'carrierwave/processing/rmagick'

class Uploader < CarrierWave::Uploader::Base
  include CarrierWave::RMagick

  def cache_dir
    "/tmp/cache"
  end

  def process_uri(uri)
    URI.parse(uri)
  end

end

class PictureUploader < Uploader

  def reprocess_file!
    cache_stored_file!
    retrieve_from_cache!(cache_name)
    recreate_versions!(:small)
  end

  version :small, :if => :is_a_small_pic? do
     ...
  end
end
```

Everything works fine on the first file generation.
It also works when i call `recreate_versions!` without any parameters. But when i call `recreate_versions!(:small)` my newly generated file will look like this `small_<filename>_small.jpg`.

Overriding `full_filename` method doesn't change anything.

**Comment by matthewvermaak** [comment] 2015-03-04 23:20
Is the only work around here to recreate all versions? or is there a fix for this?

**Comment by thomasfedb** [comment] 2015-11-28 10:35
@synoptase Is this bug still present in the latest version of carrierwave?

**Comment by synoptase** [comment] 2015-11-28 16:57
Haven't updated my carrierwave gem lately. Don't plan to until at least january.

**Comment by thomasfedb** [comment] 2015-11-30 01:03
@synoptase what version are you using?

**Comment by synoptase** [comment] 2015-12-03 15:36
Something like this:
```
carrierwave (0.10.0)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      json (>= 1.7)
      mime-types (>= 1.16)
    carrierwave-mongoid (0.7.1)
      carrierwave (>= 0.8.0, < 0.11.0)
      mongoid (>= 3.0, < 5.0)
      mongoid-grid_fs (>= 1.3, < 3.0)
    carrierwave_direct (0.0.14)
      carrierwave
      fog
      uuidtools
```

**Comment by thomasfedb** [comment] 2015-12-04 04:40
Thanks @synoptase, you're using the latest version.

**Comment by Grafikart** [comment] 2017-11-02 17:13
It looks like `filename` is called when doing a recreate_versions! (I'm using 1.2.1). I don't thinks it's the desired behaviour since it should use the name in the database and add the version name (like it does when calling model.image.{version_name}.url)

**Comment by mshibuya** [comment] 2021-10-30 08:25
Could not reproduce, maybe because #1879 have changed the version recreation much.
Please let us know if this is still an issue.

**Closed by mshibuya** 2021-10-30 08:25 UTC
Labels: bug
