### ISSUE TITLE
Rails 5.1.1 deprecation warning

### ISSUE THREAD

**Issue by oni7uka** [carrierwaveuploader/carrierwave#2181] opened 2017-05-20 03:17 UTC
I‘m using carrierwave master branch, My tests are flooded with rails deprecation warnings in carrierwave.

`DEPRECATION WARNING: The behavior of `attribute_changed?` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_change_to_attribute?` instead. (called from remote_cover_url= at /usr/local/bundle/bundler/gems/carrierwave-07dc4d7bd780/lib/carrierwave/orm/activerecord.rb:18)`

[https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/orm/activerecord.rb#L18](https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/orm/activerecord.rb#L18)

**Comment by matthewrudy** [comment] 2017-05-25 13:11
I get this all the time.
Just ignoring for now

**Comment by seanfcarroll** [comment] 2017-05-26 13:25
Duplicate of https://github.com/carrierwaveuploader/carrierwave/issues/2115

**Comment by matthewrudy** [comment] 2017-05-26 13:29
@seanfcarroll not sure it is.

This seems to come out of the activerecords.rb and is definitely not fixed on master.

**Comment by matthewrudy** [comment] 2017-05-26 13:30
I mean, it's the same warning, but out of a different bit of the library

**Comment by pedroadame** [comment] 2017-06-26 07:54
`bundle update carrierwave` solved it for me.

**Comment by CD1212** [comment] 2017-06-30 11:18
Even after a `bundle update` when on master, I'm still getting a deprecation warning from `lib/carrierwave/orm/activerecord.rb:67`

**Comment by pedroadame** [comment] 2017-06-30 11:24
I'm not on master, @CD1212, last release on rubygems, if it helps.

**Comment by matthewrudy** [comment] 2017-06-30 12:16
FYI: I found that my problem was that we did the carrierwave upload inside an `after_save` callback.

That's why it hit the deprecation warning.

**Comment by CD1212** [comment] 2017-06-30 13:06
My situation is exactly the same, I'm using Carrierwave in `after_save`. Did you find any solution @matthewrudy or are you just ignoring the warnings?

**Comment by matthewrudy** [comment] 2017-07-03 18:43
@CD1212 I moved the code into a Delayed Job.

Which was a better idea anyway.

**Closed** 2019-05-01 04:15 UTC
